name: Synchronize Repository
on:
  push:
    paths:
      - folder-to-synchronize

env:
  DEST_REPO: synchronization-test-destination
  DEST_REPO_OWNER: GerardGascon
  ORIGIN_PATH: folder-to-synchronize
  DEST_PATH: folder-synchronized
  PR_MESSAGE: Update files in some folder

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup git and clone brew formula
        env:
          GH_PAT: ${{ steps.token.outputs.token }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${GH_PAT}@github.com/${DEST_REPO_OWNER}/${DEST_REPO}.git
          cd ${DEST_REPO}

          git checkout -b ${{ github.repository.name }}-${{ github.run_number }}

      - name: Copy elements
        run: |
          mkdir -p ${DEST_REPO}/${DEST_PATH}
          cp -a ${ORIGIN_PATH}/. ${DEST_REPO}/${DEST_PATH}

      - name: Create Pull Request to homebrew repo
        env:
          GH_PAT: ${{ steps.token.outputs.token }}
        run: |
          cd ${DEST_REPO}
          
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          git add .
          git commit -m "${PR_MESSAGE}"
          git push origin ${BRANCH_NAME}
          
          curl --fail-with-body -vvv -X POST https://api.github.com/repos/${DEST_REPO_OWNER}/${DEST_REPO}/pulls \
            -H "Authorization: Bearer $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"title\": \"${PR_MESSAGE}\",\"head\": \"$BRANCH_NAME\",\"base\": \"master\",\"body\": \"Automated update\"}"